# Generated by Django 5.2.4 on 2025-07-17 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sales_units', models.IntegerField(default=0)),
                ('inventory_level', models.IntegerField(default=0)),
                ('price_at_day_end', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='dashboard_app.product')),
            ],
            options={
                'verbose_name_plural': 'Product Daily Records',
                'ordering': ['date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
